### ISSUE TITLE
Traceback for non-existing package

### ISSUE THREAD

**Issue by FrostyX** [befeleme/pyp2spec#30]
When I try to run `pyp2spec` for a nonexistent package, I get a traceback

```
$ pyp2spec nonexistingpackage 

Generating configuration file
Assuming 'nonexistingpackage' is a package name
Querying PyPI for package 'nonexistingpackage'
Assuming changelog --message=Initial package
Assuming --description=This is package 'nonexistingpackage' generated automatically by pyp2spec.
Traceback (most recent call last):
  File "/usr/bin/pyp2spec", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyp2spec/pyp2spec.py", line 63, in main
    config_file = create_config(options)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyp2spec/pyp2conf.py", line 379, in create_config
    contents = create_config_contents(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyp2spec/pyp2conf.py", line 320, in create_config_contents
    summary = pkg.summary()
              ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyp2spec/pyp2conf.py", line 161, in summary
    summary = self.package_data["info"]["summary"]
              ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'info'
```

**Comment by FrostyX** [comment]
Thank you @befeleme :-)
